/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package air.com.anime.ane;

public final class Manifest {
    public static final class permission {
        public static final String RECIVER="air.com.anime.ane.mc.permission.RECIVER";
        public static final String UPDATE="com.ffcs.android.mc.permission.UPDATE";
    }
}
